apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firstdemoproject-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - demokub.vupiy.co.uk
      secretName: firstdemoproject-tls
  rules:
    - host: demokub.vupiy.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: firstdemoproject-service
                port:
                  number: 80